ERC-4626 Collect module
lens-protocol/modules pull request #9
Opened 2022-09-12 21:27 UTC by BenSparksCode

2022-10-07 14:28 UTC, vicnaum requested changes
Also adding more tests would be cool

2022-10-07 14:28 UTC, vicnaum commented on contracts/collect/ERC4626FeeCollectModule.sol
> +    uint96 collectLimit;
```suggestion
    uint96 collectLimit;
    address currency;
```

We can also do storage slot optimization here - can save us 22k gas on posts and 2k gas on collects.

2022-10-07 14:28 UTC, vicnaum commented on contracts/collect/ERC4626FeeCollectModule.sol
> +     */
```suggestion
     *
     * @inheritdoc ICollectModule
     */
```

2022-10-07 14:28 UTC, vicnaum commented on contracts/collect/ERC4626FeeCollectModule.sol
> +        if (collectLimit != 0 && currentCollects == collectLimit) {
```suggestion
        if (collectLimit != 0 && currentCollects >= collectLimit) {
```
Not important here, but for extra safety might want to consider to stick with >= instead of == (e.g. if we have multiple collects support in the future and this code gets copy-pasted)

2022-10-07 14:28 UTC, vicnaum commented on contracts/collect/ERC4626FeeCollectModule.sol
> +            // If supply() above fails, send funds directly to beneficiary
```suggestion
            // If deposit() above fails, send funds directly to beneficiary
```

2022-10-07 14:28 UTC, vicnaum commented on contracts/collect/ERC4626FeeCollectModule.sol
> +    address[] public reserves;
Is this `reserves` array used anywhere?

2022-10-07 14:28 UTC, vicnaum commented on contracts/collect/ERC4626FeeCollectModule.sol
> +     *      address currency: The currency address, must be internally whitelisted.
```suggestion
```

I guess we don't decode currency here and grab it from vault

2022-10-07 14:28 UTC, vicnaum commented on contracts/collect/ERC4626FeeCollectModule.sol
> +// SPDX-License-Identifier: AGPL-3.0-only
```suggestion
// SPDX-License-Identifier: MIT
```
@donosonaumczuk suggested to change all licenses to MIT

2022-10-07 14:29 UTC, BenSparksCode commented on contracts/collect/ERC4626FeeCollectModule.sol
> +     *      address currency: The currency address, must be internally whitelisted.
True, good catch

2022-10-07 14:30 UTC, BenSparksCode commented on contracts/collect/ERC4626FeeCollectModule.sol
> +    address[] public reserves;
No, its also not used in the Aave module. Removing from both

2022-10-07 14:33 UTC, BenSparksCode commented on contracts/collect/ERC4626FeeCollectModule.sol
> +        if (collectLimit != 0 && currentCollects == collectLimit) {
Good catch, I remember this came from the Aave module to save gas but think security safety is more important.

2022-10-10 16:58 UTC, vicnaum submitted a review, later dismissed

2022-10-11 20:52 UTC, Zer0dot approved these changes
LGTM now!

2022-10-11 20:52 UTC, Zer0dot commented on contracts/collect/ERC4626FeeCollectModule.sol
> +    function _transferFromAndDepositInVaultIfApplicable(
Very very minor comment, can we move this under `processCollectWithReferral()`?

2022-10-11 20:59 UTC, vicnaum approved these changes

2022-10-12 06:53 UTC, merged